// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLsH-F47f6w1ksMohGCaMgvyt59QBSSO0',
    appId: '1:99752408527:android:f4662503adc49a1ff74eba',
    messagingSenderId: '99752408527',
    projectId: 'the-islamic-library-30896',
    storageBucket: 'the-islamic-library-30896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCCmOtUeywFLnKMVybUuIAH5O80sMD4g',
    appId: '1:99752408527:ios:4990852fe9b0ec90f74eba',
    messagingSenderId: '99752408527',
    projectId: 'the-islamic-library-30896',
    storageBucket: 'the-islamic-library-30896.appspot.com',
    androidClientId: '99752408527-t17sg7f448d7sbe7mmmm3pj6k3ql9n64.apps.googleusercontent.com',
    iosClientId: '99752408527-62pho349ns7s2khbcj0s7eie4c73vhri.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelancer',
  );

}